# created from https://www.youtube.com/watch?v=AAJ6FTqIVMY&list=PL2We04F3Y_43dAehLMT5GxJhtk3mJtkl5&index=8
apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    costcenter: amer
    location: NA
spec:
  containers:
    - name: nginx-container
      image: nginx

    - name: backend-container
      image: redis
