apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscalling
  labels:
    app: my-k8s-deployment
spec:
  selector:
    matchLabels:
      project: xyz #Service will look at this labels!!!
  template:
    metadata:
      labels:
        project: xyz
    spec:
      containers:
        - name: xyz-web
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2betav1
    kind: Depoyment
    name: my-web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-data
  labels:
    env: prod
    owner: Siarhei_Kalashynski
spec:
  selector:
    project: xyz
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer