# copied from: https://www.youtube.com/watch?v=kGwe8IEDiX4&list=PLg5SS_4L6LYvN1RqaVesof8KAf-02fJSi&index=8&ab_channel=ADV-IT
apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    env: prod
    app: main
    tier: frontend
    owner: Siargei_Kalashynski
spec:
  containers:
    - name: container-apache
      image: nginx:latest
      ports:
        - containerPort: 80